#ifndef EXTI_CONFIG_H
#define EXTI_CONFIG_H

#define EXTI_U8_INT0_CONTROL	ENABLED
#define EXTI_U8_INT1_CONTROL	ENABLED
#define EXTI_U8_INT2_CONTROL	DISABLED

#define EXTI_U8_INT0_SENSE		FALLING_EDGE
#define EXTI_U8_INT1_SENSE		FALLING_EDGE
#define EXTI_U8_INT2_SENSE		FALLING_EDGE



#endif
