#ifndef SEVENSEGMENT_CONFIG_H_
#define SEVENSEGMENT_CONFIG_H_

#define MODE				COMMON_CATHODE

#define SEVENSEG_PINA_PORT 		PORT_A
#define SEVENSEG_PINA_NUMBER 	PIN0
#define SEVENSEG_PINB_PORT 		PORT_A
#define SEVENSEG_PINB_NUMBER 	PIN1
#define SEVENSEG_PINC_PORT 		PORT_A
#define SEVENSEG_PINC_NUMBER 	PIN2
#define SEVENSEG_PIND_PORT 		PORT_A
#define SEVENSEG_PIND_NUMBER 	PIN3
#define SEVENSEG_PINE_PORT 		PORT_A
#define SEVENSEG_PINE_NUMBER 	PIN4
#define SEVENSEG_PINF_PORT 		PORT_A
#define SEVENSEG_PINF_NUMBER 	PIN5
#define SEVENSEG_PING_PORT 		PORT_A
#define SEVENSEG_PING_NUMBER 	PIN6
#define SEVENSEG_PINH_PORT 		PORT_A
#define SEVENSEG_PINH_NUMBER 	PIN7

#define SEVENSEG_PINCOM1_PORT 	PORT_C
#define SEVENSEG_PINCOM1_NUMBER PIN0
#define SEVENSEG_PINCOM2_PORT   PORT_C
#define SEVENSEG_PINCOM2_NUMBER PIN1


#endif
