#ifndef EXTI_CONFIG_H
#define EXTI_CONFIG_H

#define EXTI_U8_INT0_CONTROL	ENABLED
#define EXTI_U8_INT1_CONTROL	ENABLED
#define EXTI_U8_INT2_CONTROL	ENABLED

#define EXTI_U8_INT0_SENSE		RISING_EDGE
#define EXTI_U8_INT1_SENSE		RISING_EDGE
#define EXTI_U8_INT2_SENSE		RISING_EDGE

#endif
